### ISSUE TITLE
Rename github master branch to main

### ISSUE THREAD

**Issue by andygrove** [ballista-compute/sqlparser-rs#213]
Rename github master branch to main

**Comment by maxcountryman** [comment]
Happy to take a crack at this. Should be fairly straightforward, we'll need to create `main`, update a few references, and then set it as the default branch. I can push up the branch and ensure it's inline with our old mainline and then put together a PR to update references before we switch the default branch.

**Comment by andygrove** [comment]
Perfect. Existing PRs can be edited to change the base branch easily once the main branch exists.

And for context on why this change is being made (I should have included this information when creating the issue):

https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/

**Comment by maxcountryman** [comment]
I've created the `main` branch and put together a PR of the references in the README and CHANGELOG that needed updating. @andygrove I think you'll have to update the default branch when you're ready.

**Comment by andygrove** [comment]
`main` is now the default branch.
