### ISSUE TITLE
Add unit tests for TPCH queries

### ISSUE THREAD

**Issue by andygrove** [ballista-compute/sqlparser-rs#220]
I've started work on making Ballista capable of running the TPCH benchmark and plan on using the latest version of the sqlparser crate. 

It would be nice to add the TPCH queries [1] to the unit/integration tests to make sure they can all be parsed correctly. If we need to pick a dialect to test with, I would suggest Hive.

[1] https://github.com/andygrove/tpch-dbgen/tree/master/queries

**Comment by Dandandan** [comment]
Good idea. Also linked to TPC-DS in this issue
https://github.com/ballista-compute/sqlparser-rs/issues/212

**Comment by Dandandan** [comment]
Added a PR here https://github.com/ballista-compute/sqlparser-rs/pull/221

FYI, nr 6 and 22 are failing currently:


```sql

select
	sum(l_extendedprice * l_discount) as revenue
from
	lineitem
where
	l_shipdate >= date '1994-01-01'
	and l_shipdate < date '1994-01-01' + interval '1' year
	and l_discount between .06 - 0.01 and .06 + 0.01
	and l_quantity < 24;
```

```sql

select
	cntrycode,
	count(*) as numcust,
	sum(c_acctbal) as totacctbal
from
	(
		select
			substring(c_phone from 1 for 2) as cntrycode,
			c_acctbal
		from
			customer
		where
			substring(c_phone from 1 for 2) in
				('13', '31', '23', '29', '30', '18', '17')
			and c_acctbal > (
				select
					avg(c_acctbal)
				from
					customer
				where
					c_acctbal > 0.00
					and substring(c_phone from 1 for 2) in
						('13', '31', '23', '29', '30', '18', '17')
			)
			and not exists (
				select
					*
				from
					orders
				where
					o_custkey = c_custkey
			)
	) as custsale
group by
	cntrycode
order by
	cntrycode;
```

**Comment by Dandandan** [comment]
PR #221 is merged, can address the ignored tests (6, 22) later.
