### ISSUE TITLE
cte inside select

### ISSUE THREAD

**Issue by hwchen** [ballista-compute/sqlparser-rs#222]
I've recently come across sql queries where the cte was inside of a SELECT statement:

```
SELECT * FROM (WITH x AS (SELECT...) SELECT y from x) "zzz" where (0 = 1)
```
Should this be supported, or is this a dialect oddity? (Snowflake)

**Comment by Dandandan** [comment]
Thanks for filing the issue.
Did you test this already in the parser? I believe this should supported already, otherwise it looks like a bug.

**Comment by hwchen** [comment]
So strange, I could have sworn it was failing a test. Perhaps I misread it. Anyways, I see how this is supported, and I also see the test for it. Sorry!
