### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by Dandandan** [ballista-compute/sqlparser-rs#231]
I would like to release a new version, as it has support for the `ASSERT` statement.

Any objections?

Should we call it 0.5.2 or 0.6?

**Comment by nickolay** [comment]
No objections from me, and [it's probably better to call it 0.6](https://github.com/ballista-compute/sqlparser-rs/issues/117#issuecomment-507819462).

**Comment by Dandandan** [comment]
Thanks. I released a new version. By accident I merged the `master` branch as 0.6.0 instead of the `main` branch.

Removed the master branch now to avoid confusion in the future. Also we might want to automate `cargo publish` as well.

**Comment by maxcountryman** [comment]
@Dandandan I can help with the release automation. 🙂

**Comment by Dandandan** [comment]
That would be awesome @maxcountryman . I looked at adding a cargo token earlier to the repo, but looks like I don't have sufficient permissions to do that.
