### ISSUE TITLE
Add semicolon to the end of the `ALTER ` SQL, test will panic

### ISSUE THREAD

**Issue by mashuai** [ballista-compute/sqlparser-rs#233]
I change the test in `sqlparser_common.rs` https://github.com/ballista-compute/sqlparser-rs/blob/f053383c718b3d4942751224783c594ff7e9f0b1/tests/sqlparser_common.rs#L1380
change `"ALTER TABLE tab ADD COLUMN foo TEXT"` to `"ALTER TABLE tab ADD COLUMN foo TEXT;"`, add a semicolon at the end of the SQL, when I rerun the test it reports   
```
---- parse_alter_table stdout ----
thread 'parse_alter_table' panicked at 'called `Result::unwrap()` on an `Err` value: ParserError("Expected column option, found: ;")', src/test_utils.rs:70:30
```

**Comment by nickolay** [comment]
Yeah, seems like in #203 we should have made [the `match` in `parse_column_def`](https://github.com/ballista-compute/sqlparser-rs/blob/f053383c718b3d4942751224783c594ff7e9f0b1/src/parser.rs#L1183) context-dependent...
