### ISSUE TITLE
Do we support subqueries on JOIN?

### ISSUE THREAD

**Issue by jorgecarleitao** [ballista-compute/sqlparser-rs#236]
I have been unable to parse this query: `SELECT a FROM simple1 JOIN (SELECT a, b FROM simple2) AS foo ON a`, with the error 

```
ParserError("Unexpected token at end of SELECT: RParen")
```

**Comment by nickolay** [comment]
Works for me on 0.6.1 (f053383c718b3d4942751224783c594ff7e9f0b1)!

**Comment by jorgecarleitao** [comment]
yeap, my bad not using the latest version. Sorry about the noise :(

**Comment by nickolay** [comment]
No problem! Note that this was added more than a year ago though.

**Comment by jorgecarleitao** [comment]
Yeah, I was testing [with 0.2.6](https://github.com/apache/arrow/blob/master/rust/datafusion/Cargo.toml#L50). I will try to bump it (https://issues.apache.org/jira/browse/ARROW-7903)
