### ISSUE TITLE
Minor typo in format of FileFormat::Json

### ISSUE THREAD

**Issue by jorgecarleitao** [ballista-compute/sqlparser-rs#237]
We can read `JSONFILE => "TEXTFILE"` on [this line](https://github.com/ballista-compute/sqlparser-rs/blob/583f22b92900c7096ae29fd6b5280e27d93884c4/src/ast/mod.rs#L895) - it should be `JSONFILE => "JSONFILE"`

**Comment by nickolay** [comment]
Thanks, fixed!
