### ISSUE TITLE
PREPARE, EXECUTE and DEALLOCATE are not top-level statements

### ISSUE THREAD

**Issue by silathdiir** [ballista-compute/sqlparser-rs#242]
Hi, I am using this crate to parse SQLs, and working on [Postgres Extended Query](https://www.postgresql.org/docs/current/sql-prepare.html#SQL-PREPARE-EXAMPLES). e.g.

```
prepare stmt (smallint) AS select * from schema_name.table_name where si_column_2 = $1;
execute stmt(1, 2);
deallocate stmt;
```

I tried to find solutions by `Dialect`, but it seems that `PREPARE`, `EXECUTE` and `DEALLOCATE` are not top-level statements.

Should they be added as top-level statements? Or there are other better solutions. Thanks.

**Comment by nickolay** [comment]
Yes, adding them as new `Statement` variants is how we do that. Please note that it's Postgres-specific syntax in the comments.
