### ISSUE TITLE
README.md wrong syntax in example: feature => features 

### ISSUE THREAD

**Issue by aisbergde** [ballista-compute/sqlparser-rs#269]
The syntax in the example is wrong

>D:\Repos\GitHub\sqlparser-rs\examples>cargo run --feature json_example --example cli FILENAME.sql
>error: Found argument '--feature' which wasn't expected, or isn't valid in this context
>        Did you mean --features?
>
>USAGE:
>    cargo.exe run --features <FEATURES>...
>
>For more information try --help

it should be --features

I never used Rust before. I don't plane to be a rust developer, I am a database specialist. But of course I am ready to learn some basics. That's why examples are important and it should be easy to use them.

You could add some more first step documentation:
- install rust using rustup
- use the examples by calling: ...
- what to do to convert the example script into an application which can be uses outside the current project

**Comment by nickolay** [comment]
Thanks, I fixed the typo in the README.

If you're willing to submit specific improvements in a PR, that would be welcome as well!

I don't think we're ready to be marketed to people, who are not ready to learn Rust, yet, as we only have enough manpower to merge PRs.
