### ISSUE TITLE
parse_infix: return error instead of panic

### ISSUE THREAD

**Issue by BohuTANG** [ballista-compute/sqlparser-rs#314]
Hello,

Great sql parser in Rust!
We have used it in [datafuse](https://github.com/datafuselabs/datafuse) and works well.
But it always crashed under fuzzer due to the panics in:
https://github.com/ballista-compute/sqlparser-rs/blob/35ef0eee3857c59827b2587bc813218a00dce264/src/parser.rs#L809

Fuzz panic error stack:
```
(lldb) r
thread 'main' panicked at 'No infix parser for token RBracket', /home/bohu/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/sqlparser-0.9.0/src/parser.rs:897:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/657bc01888e6297257655585f9c475a0801db6d2/library/std/src/panicking.rs:515:5
   1: std::panicking::begin_panic_fmt
             at /rustc/657bc01888e6297257655585f9c475a0801db6d2/library/std/src/panicking.rs:457:5
   2: sqlparser::parser::Parser::parse_infix
             at /home/bohu/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/sqlparser-0.9.0/src/parser.rs:897:13
   3: sqlparser::parser::Parser::parse_subexpr
             at /home/bohu/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/sqlparser-0.9.0/src/parser.rs:296:20
   4: sqlparser::parser::Parser::parse_expr
             at /home/bohu/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/sqlparser-0.9.0/src/parser.rs:280:9
   5: sqlparser::parser::Parser::parse_assert
             at /home/bohu/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/sqlparser-0.9.0/src/parser.rs:301:25
   6: sqlparser::parser::Parser::parse_statement
             at /home/bohu/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/sqlparser-0.9.0/src/parser.rs:160:39
   7: fuse_query::sql::sql_parser::DfParser::parse_statement
             at /home/bohu/github/datafuselabs/datafuse/fusequery/query/src/sql/sql_parser.rs:143:51
   8: fuse_query::sql::sql_parser::DfParser::parse_sql_with_dialect
             at /home/bohu/github/datafuselabs/datafuse/fusequery/query/src/sql/sql_parser.rs:93:29
   9: fuse_query::sql::sql_parser::DfParser::parse_sql
             at /home/bohu/github/datafuselabs/datafuse/fusequery/query/src/sql/sql_parser.rs:69:12
  10: fuzz_parse_sql::main::{{closure}}
             at ./fuzz_targets/fuzz_parse_sql.rs:11:21
  11: honggfuzz::fuzz
             at /home/bohu/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/honggfuzz-0.5.54/src/lib.rs:316:5
  12: fuzz_parse_sql::main
             at ./fuzz_targets/fuzz_parse_sql.rs:10:9
  13: core::ops::function::FnOnce::call_once
             at /rustc/657bc01888e6297257655585f9c475a0801db6d2/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

It would be better return error instead of the panic.

Fuzz codes here:
https://github.com/datafuselabs/datafuse/tree/6a03aded7b0df5ce18a76162f0f10c59966e5084/fusequery/fuzz

**Comment by Dandandan** [comment]
> Hello,
> 
> Great sql parser in Rust!
> We have used it in [datafuse](https://github.com/datafuselabs/datafuse) and works well.
> But it always crashed under fuzzer due to the panics in:
> https://github.com/ballista-compute/sqlparser-rs/blob/35ef0eee3857c59827b2587bc813218a00dce264/src/parser.rs#L809
> 
> Fuzz panic error stack:
> 
> ```
> (lldb) r
> thread 'main' panicked at 'No infix parser for token RBracket', /home/bohu/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/sqlparser-0.9.0/src/parser.rs:897:13
> stack backtrace:
>    0: rust_begin_unwind
>              at /rustc/657bc01888e6297257655585f9c475a0801db6d2/library/std/src/panicking.rs:515:5
>    1: std::panicking::begin_panic_fmt
>              at /rustc/657bc01888e6297257655585f9c475a0801db6d2/library/std/src/panicking.rs:457:5
>    2: sqlparser::parser::Parser::parse_infix
>              at /home/bohu/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/sqlparser-0.9.0/src/parser.rs:897:13
>    3: sqlparser::parser::Parser::parse_subexpr
>              at /home/bohu/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/sqlparser-0.9.0/src/parser.rs:296:20
>    4: sqlparser::parser::Parser::parse_expr
>              at /home/bohu/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/sqlparser-0.9.0/src/parser.rs:280:9
>    5: sqlparser::parser::Parser::parse_assert
>              at /home/bohu/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/sqlparser-0.9.0/src/parser.rs:301:25
>    6: sqlparser::parser::Parser::parse_statement
>              at /home/bohu/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/sqlparser-0.9.0/src/parser.rs:160:39
>    7: fuse_query::sql::sql_parser::DfParser::parse_statement
>              at /home/bohu/github/datafuselabs/datafuse/fusequery/query/src/sql/sql_parser.rs:143:51
>    8: fuse_query::sql::sql_parser::DfParser::parse_sql_with_dialect
>              at /home/bohu/github/datafuselabs/datafuse/fusequery/query/src/sql/sql_parser.rs:93:29
>    9: fuse_query::sql::sql_parser::DfParser::parse_sql
>              at /home/bohu/github/datafuselabs/datafuse/fusequery/query/src/sql/sql_parser.rs:69:12
>   10: fuzz_parse_sql::main::{{closure}}
>              at ./fuzz_targets/fuzz_parse_sql.rs:11:21
>   11: honggfuzz::fuzz
>              at /home/bohu/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/honggfuzz-0.5.54/src/lib.rs:316:5
>   12: fuzz_parse_sql::main
>              at ./fuzz_targets/fuzz_parse_sql.rs:10:9
>   13: core::ops::function::FnOnce::call_once
>              at /rustc/657bc01888e6297257655585f9c475a0801db6d2/library/core/src/ops/function.rs:227:5
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> ```
> 
> It would be better return error instead of the panic.
> 
> Fuzz codes here:
> https://github.com/datafuselabs/datafuse/tree/6a03aded7b0df5ce18a76162f0f10c59966e5084/fusequery/fuzz

Thanks @BohuTANG. I agree an error instead of panicking would be a good improvement.

**Comment by BohuTANG** [comment]
If there's no plan, I'm glad to take this issue :dancers:
